learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls'), namespace='learning_logs')),
    path('', include(('users.urls'), namespace='users')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.conf.urls import url
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Redirects of all locations
    url(r'^barn/$', views.tavern, name='barn'),
    url(r'^church/$', views.tavern, name='church'),
    url(r'^market/$', views.tavern, name='market'),
    url(r'^park/$', views.tavern, name='park'),
    url(r'^residential/$', views.tavern, name='residential'),
    url(r'^tavern/$', views.tavern, name='tavern'),

    # Leads to listings of citizens personal details
    url(r'^citizen_details/$', views.citizen_details, name='citizen-details'),

    # Page with a master list of all citizens
    url(r'^citizen_roster/$', views.citizen_roster, name='citizen-roster'),

    # Confirm on termination
    url(r'^confirm/$', views.confirm, name='confirm'),

    # Overview maps page
    url(r'^map/$', views.map, name='map'),

    # Page with reports on citizens
    url(r'^reports/$', views.reports, name='reports'),
]

users/urls.py
"""Defines URL patterns for users."""

from django.conf.urls import url
from django.contrib.auth import login

from . import views

app_name = 'users'

urlpatterns = [
    # Login page 
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page
    url(r'^register/$', views.register, name='register')
]

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Building(models.Model):
    locid = models.ForeignKey('Location', models.DO_NOTHING, db_column='LocID')  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=40)  # Field name made lowercase.
    capacity = models.IntegerField(db_column='Capacity')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'building'


class Camera(models.Model):
    secid = models.ForeignKey('Secsystem', models.DO_NOTHING, db_column='SecID')  # Field name made lowercase.
    alerts = models.IntegerField(db_column='Alerts', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'camera'


class Citizen(models.Model):
    citizenid = models.IntegerField(db_column='CitizenID', primary_key=True)  # Field name made lowercase.
    fname = models.CharField(db_column='FName', max_length=30)  # Field name made lowercase.
    lname = models.CharField(db_column='LName', max_length=30)  # Field name made lowercase.
    age = models.IntegerField(db_column='Age')  # Field name made lowercase.
    birthday = models.DateField(db_column='Birthday')  # Field name made lowercase.
    locid = models.ForeignKey('Location', models.DO_NOTHING, related_name='LocID')  # Field name made lowercase.
    homeid = models.ForeignKey('Location', models.DO_NOTHING, related_name='HomeID')  # Field name made lowercase.
    strikes = models.IntegerField(db_column='Strikes')  # Field name made lowercase.
    isalive = models.IntegerField(db_column='IsAlive')  # Field name made lowercase.
    income = models.IntegerField(db_column='Income')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'citizen'


class Contraband(models.Model):
    itemid = models.AutoField(db_column='ItemID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=40)  # Field name made lowercase.
    currentowner = models.ForeignKey(Citizen, models.DO_NOTHING, related_name='CurrentOwner', blank=True, null=True)  # Field name made lowercase.
    originalowner = models.ForeignKey(Citizen, models.DO_NOTHING, related_name='OriginalOwner', blank=True, null=True)  # Field name made lowercase.
    threatlevel = models.IntegerField(db_column='ThreatLevel', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'contraband'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Location(models.Model):
    locid = models.CharField(db_column='LocID', primary_key=True, max_length=4)  # Field name made lowercase.
    secid = models.ForeignKey('Secsystem', models.DO_NOTHING, db_column='SecID', blank=True, null=True)  # Field name made lowercase.
    threatlevel = models.IntegerField(db_column='ThreatLevel')  # Field name made lowercase.
    curfew = models.IntegerField(db_column='Curfew', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'location'


class Secsystem(models.Model):
    secid = models.IntegerField(db_column='SecID', primary_key=True)  # Field name made lowercase.
    status = models.IntegerField(db_column='Status', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'secsystem'


class Socialstanding(models.Model):
    citizenid = models.ForeignKey(Citizen, models.DO_NOTHING, db_column='CitizenID')  # Field name made lowercase.
    talents = models.CharField(db_column='Talents', max_length=40, blank=True, null=True)  # Field name made lowercase.
    charm = models.IntegerField(db_column='Charm')  # Field name made lowercase.
    score = models.IntegerField(db_column='Score')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'socialstanding'


class World(models.Model):
    clock = models.IntegerField(db_column='Clock')  # Field name made lowercase.
    datecount = models.DateField(db_column='DateCount')  # Field name made lowercase.
    humidity = models.IntegerField(db_column='Humidity')  # Field name made lowercase.
    temp = models.IntegerField(db_column='Temp')  # Field name made lowercase.
    precip = models.CharField(db_column='Precip', max_length=20, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'world'

learning_logs/forms.py
# from django import forms
#
#
# class IndexForm(forms.Form):
#     name = forms.CharField(label="uname", max_length=100)

learning_logs/views.py
from django.shortcuts import render


# Master list of all html page redirects
def index(request):
    """The home page for application"""
    return render(request, 'learning_logs/index.html')


def map(request):
    """The map page"""
    return render(request, 'learning_logs/map.html')


def reports(request):
    """Citizens reports for individual people"""
    return render(request, 'learning_logs/reports.html')


def citizen_details(request):
    """Citizens report details for individual people"""
    return render(request, 'learning_logs/citizen-details.html')


def citizen_roster(request):
    """Master roster for all the citizens"""
    return render(request, 'learning_logs/citizen-roster.html')


def tavern(request):
    """Basic loading page for locations switches depending on the location"""
    return render(request, 'learning_logs/tavern.html')


def confirm(request):
    return render(request, 'learning_logs/confirm.html')

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        <link rel="stylesheet" type="text/css" href="{% static "learning_logs/footer.css" %}">
    </head>

    <body style="background-color: orange; width: 95%; margin:110px" class="container" >
      <div class="container-sp" style="height:2300px; width:100%">
        {% block header %} {% endblock header %}
      </div>
      <div>
        {% block content %} {% endblock content %}
      </div>
      <div class="holder"></div>
    </body>
</html>

learning_logs/templates/learning_logs/camera.html
<h1>What's up</h1>
{#{% load bootstrap3 %}#}
{#{% load static %}#}
{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
/Users/ra060639/Desktop/InternHack-master/learning_logs/templates/learning_logs/camera.html
/Users/ra060639/Desktop/InternHack-master/learning_logs/templates/learning_logs/map.html

{##}
{#    <head>#}
{#        <meta charset="utf-8">#}
{#        <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#        <meta name="viewport" content="width=device-width, initial-scale=1">#}
{##}
{#        <title>Silver</title>#}
{##}
{#        <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>#}
{#        {% bootstrap_css %}#}
{#        {% bootstrap_javascript %}#}
{#        <link rel="stylesheet" type="text/css" href="{% static "learning_logs/footer.css" %}">#}
{#        <link rel="icon" type="image/png" href="{% static "learning_logs/favicon.ico" %}" />#}
{#    </head>#}
{##}
{#    <body style="background-color: orange; width: 95%; margin:110px" class="container" >#}
{#      <div class="container" style="width:80%; height:60%;">#}
{#        <div class="container-sp-camera" style="height:2300px; width:100%">#}
{#            <!-- Static Navbar -->#}
{#        <nav class="navbar navbar-default bg-inverse navbar-static-top ">#}
{#            <div class="container">#}
{#                <div class="navbar-header">#}
{#                    <button type="button" class="navbar-toggle collapsed"#}
{#                        data-toggle="collapse" data-target="#navbar"#}
{#                        aria-expanded="false" aria-controls="navbar">#}
{#                    </button>#}
{#                </div>#}
{##}
{#                <div id="navbar" class="navbar-collapse collapse">#}
{##}
{#                <div class="text-primary"></div>#}
{#                    <ul class="nav navbar-nav navbar-left">#}
{#                        {% if user.is_authenticated %}#}
{#                            <h1><a class="words">Welcome Back, {{ user.username }}</a></h1>#}
{#                            <h1><a href="{% url 'learning_logs:medications' %}"><header>Medications</header></a></h1>#}
{#                            <h1><a href="{% url 'learning_logs:camera' %}">camera</a></h1>#}
{#                            <h1><a href="{% url 'users:logout' %}">Logout</a></h1>#}
{#                        {% else %}#}
{#                            <h1><a href="{% url 'users:register' %}">Register</a></h1>#}
{#                            <h1><a href="{% url 'learning_logs:camera' %}">camera</a></h1>#}
{#                            <h1><a href="{% url 'users:login' %}">Login</a></h1>#}
{#                        {% endif %}#}
{#                    </ul>#}
{#                </div> <!--/.nav-collapse-->#}
{#            </div>#}
{#        </nav>#}
{#        </div>#}
{#      </div>#}
{#    </body>#}

learning_logs/templates/learning_logs/citizen-details.html
<!DOCTYPE html>
<html>
<head>
	<title>Citizen Details</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> 
	<script>
	function goBack() {
    window.history.back();
}
</script>
</head>
<body>

	<header id="main-header">
		<div class="header-image">
			<img src="/static/learning_logs/hv_logo.png">
			<a class="plain-button" href="{% url 'learning_logs:index' %}">Main Control Screen</a>
		</div>
	</header>

	<div class="plain-box">
		<div class="citizen-header">
  			<h1>Citizen Name</h1>
  			<img src="/static/learning_logs/outline.png"/>
		</div>
		
		<div class="clr"></div>

		<div class="item-details">
			<ul>
			<li>Citizen ID: </li>
			<li>Current Location: </li>
			</ul>

			<hr>

			<ul>
			<li>Age: </li>
			<li>Birthday: </li>
			<li>Residence: </li>
			<li>Strikes: </li>
			<li>Income</li>
			</ul>
		</div>
		
		<div class="plain-area">
			<button class="plain-button" onclick="goBack()">Go Back</button>
		</div>	
	</div>

	<footer id="main-footer">
		<p>Happyville Inc.</p>
			<hr>
			<hr>
			<hr>
		<div class="plain-area">
			<a class="button red-button" href="{% url 'learning_logs:confirm' %}">Do Not Push</a>
		</div>
	</footer>

</body>
</html>

learning_logs/templates/learning_logs/citizen-roster.html
<!DOCTYPE html>
<html>
<head>
	<title>Citizen Roster</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> 
</head>
<body>
	
	<header id="main-header">
		<div class="header-image">
			<img src="/static/learning_logs/hv_logo.png">
			<a class="plain-button" href="{% url 'learning_logs:index' %}">Main Control Screen</a>
		</div>
	</header>

	<div class="plain-box">
		<div class="citizen-header">
  			<h1>Citizen Name</h1>
  			<img src="/static/learning_logs/outline.png"/>
		</div>
		
		<div class="clr"></div>

		<div class="item-details">
			<ul>
			<li>Citizen ID: </li>
			<li>Current Location: </li>
			</ul>
		</div>
			
		<div class="plain-area">
			<a class="plain-button" href="{% url 'learning_logs:citizen-details' %}">More Details...</a>
		</div>
	</div>

	<footer id="main-footer">
		<p>Happyville Inc.</p>
	</footer>

</body>
</html>

learning_logs/templates/learning_logs/citizen_report.html
<h1>List the people here</h1>

learning_logs/templates/learning_logs/confirm.html
<!DOCTYPE html>
<html>
<head>
	<title>Terminated</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> </head>
<body>
	<div class="plain-box">
		<h1>Are you sure?</h1>
		<hr>
		<div class="plain-area">
			<a class="button red-button" href="{% url 'learning_logs:citizen-roster' %}">Yes I am sure</a>
		</div>
	</div>
</body>
</html>






learning_logs/templates/learning_logs/home.html
<!DOCTYPE html>
<html>

<head>
	<title>Happyville Control Center</title>
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> 

</head>

<body>

	<header id="main-header">
		<div class="header-image">
			<img src="../happyville/images/hv_logo.png">
			<h1>Happyville Control Center</h1>	
		</div>
	</header>

{#	<!-- Container -->#}
{#	<div class="container">#}
{#		#}
{#		<!-- Screen Image -->#}
{#		<img class="img"src="images/test.png" alt="Sorry about that" draggable="false">#}
{#		#}
{#		<!-- Top Buttons -->#}
{#		<div class="button-group-1">#}
{#			<a class="button" href="map.html">Map</a>#}
{#			<a class="button" href="reports.html">Reports</a>#}
{#			<a class="button" href="citizen-roster.html">Citizen Roster</a>#}
{#		</div>#}
{##}
{#		<div class="clr"></div>#}
{##}
{#		<!-- Side Buttons -->#}
{#		<div class="button-group-2">#}
{#			<a class="button" href="church.html">Church</a>#}
{#			<a class="button" href="tavern.html">Tavern</a>#}
{#			<a class="button" href="barn.html">Barn</a>#}
{#			<a class="button" href="park.html">Park</a>#}
{#			<a class="button" href="market.html">Market</a>#}
{#			<a class="button" href="residential.html">Residential</a>#}
{##}
{#		</div>#}
{#	</div>#}

{#	<div class="plain-box">#}
{#		<h1>Status and details</h1>	#}
{#			<div class="plain-area">#}
{#				<div class="item-details">#}
{#					<ul>#}
{#						<li>Stuff</li>#}
{#						<li>Stuff</li>#}
{#						<li>Stuff</li>#}
{#						<li>Stuff</li>#}
{#					</ul>#}
{#				</div>#}
{#			</div>#}
{#	</div>#}
{##}
{#	<footer id="main-footer">#}
{#	<p>Happyville Inc.</p>#}
{#	<hr>#}
{#	<hr>#}
{#	<hr>#}
{#	</footer>#}

</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block header %}

  <body class="container">
    <div class="container colMS">
      <h1 style="font-size: 280px; color: white; margin-top: 180px; text-align: center">HAPPY VILLIAGE</h1>
      <h1 class="centered text" style="font-size: 120px; margin-top: 50px; text-align: center"><a href="{% url 'learning_logs:map' %}">Map</a></h1><br>
      <h1 class="centered" style="font-size: 120px; text-align: center"><a href="{% url 'learning_logs:reports' %}">Reports</a></h1><br>
      <h1 class="centered" style="font-size: 120px; text-align: center"><a href="{% url 'learning_logs:citizen-roster' %}">Citizen_Roster</a></h1><br>
    </div>
  </body>

{% endblock header %}

{% block content %}

{% endblock content %}

learning_logs/templates/learning_logs/map.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>

<html>

<head>
	<title>Happyville Control Center</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css">
</head>

<body>
	<header id="main-header">
		<div class="header-image">
			<img src="/static/learning_logs/hv_logo.png">
			<h1>Happyville Control Center</h1>
		</div>
	</header>

	<!-- Container -->
	<div class="container">

		<!-- Screen Image -->
		<img class="img" src="/static/learning_logs/town.jpg" alt="Sorry about that" draggable="false">

		<!-- Top Buttons -->
		<div class="button-group-1">
			<a class="button" href="{% url 'learning_logs:map' %}">Map</a>
			<a class="button" href="{% url 'learning_logs:reports' %}">Reports</a>
			<a class="button" href="{% url 'learning_logs:citizen-roster' %}">Citizen Roster</a>
		</div>

		<div class="clr"></div>

		<!-- Side Buttons -->
		<div class="button-group-2">
			<a class="button" href="{% url 'learning_logs:tavern' %}">Church</a>
			<a class="button" href="{% url 'learning_logs:tavern' %}">Tavern</a>
			<a class="button" href="{% url 'learning_logs:tavern' %}">Barn</a>
			<a class="button" href="{% url 'learning_logs:tavern' %}">Park</a>
			<a class="button" href="{% url 'learning_logs:tavern' %}">Market</a>
			<a class="button" href="{% url 'learning_logs:tavern' %}">Residential</a>
		</div>
	</div>

	<div class="plain-box">
		<h1>Status and details</h1>
			<div class="plain-area">
				<div class="item-details">
					<ul>
						<li>Stuff</li>
						<li>Stuff</li>
						<li>Stuff</li>
						<li>Stuff</li>
					</ul>
				</div>
			</div>
	</div>
</body>
<footer id="main-footer">
	<p>Happyville Inc.</p>
</footer>

</html>

learning_logs/templates/learning_logs/reports.html
<!DOCTYPE html>
<html>
<head>
	<title>Happyville Map</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> 
</head>
<body>

	<header id="main-header">
		<div class="header-image">
			<img src="/static/learning_logs/hv_logo.png">
			<a class="plain-button" href="{% url 'learning_logs:index' %}">Main Control Screen</a>
		</div>
	</header>

	<div class="plain-box">
		<h1>Test</h1>
		<button class="plain-button">111</button>
		<button class="plain-button">222</button>
		<button class="plain-button">333</button>
	</div>

	<div class="plain-area">
		<p>Select from these Fast Reports: </p>
		<select class="plain-button">
			<option value="Watchlist">Citizens who are on the Watchlist</option>
			<option value="susp-areas">Suspicous areas</option>
			<option value="most-citizens">Location with the most citizens</option>
			<option value="tot-income">Total income of Happyville</option>
		</select> 

		<p>Search for a citizen by name: </p>
		<form class="input-form">
			<div class="form-group">
					<label>Citizen Name: </label>
					<input type="text" name="name">
			</div>
			<input class="button" type=submit value="Search" name"">
		</form>
		
		<p>Search area by name: </p>
		<form class="input-form">
			<div class="form-group">
					<label>Area Name: </label>
					<input type="text" name="name">
			</div>
			<input class="button" type=submit value="Search" name"">
		</form>
	</div>

	<footer id="main-footer">
		<p>Happyville LTD</p>
	</footer>

</body>
</html>

learning_logs/templates/learning_logs/tavern.html
<!DOCTYPE html>
<html>
<head>
	<title>Happyville Map</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> 
</head>
<body>

	<header id="main-header" style="background-color: #666; margin-bottom: 10px; padding: 2px;">
		<div class="header-image" style="display: block; width: 100%; margin: 5px;">
			<img src="/static/learning_logs/hv_logo.png">
			<a class="plain-button"  style="text-align: center; background-color: black;
              margin-top: 20px; border-radius: 50px; padding: 22px; width: 350px; text-decoration: none;
              color: #fff; font-family: SFPixelateRegular, tahoma, helvetica, serif; float: right; margin-right: 35px; font-size: small; line-height: 40px" href="{% url 'learning_logs:map' %}">Main Control Screen</a>
		</div>
	</header>
	
	<div class="plain-box" style="background-color: #666; border-style: none !important; padding: 0 !important;">
		<div class="location-header" style="display: none; margin: 15px; padding: 1%; box-sizing: border-box;">
			<h1>Location: Tavern</h1>
		</div>

		<div class="clr"></div>

		<div class="item-details" style="display: block; border-color: #333; border-width: 2px; border-style: inset; margin: auto; font-size: 50px; line-height: 1.6em;">
				<!-- Screen Image -->
		<img class="img" src="/static/learning_logs/town.jpg" alt="Sorry about that" draggable="false">

		<!-- Top Buttons -->
		<div class="button-group-tavern">
			<a class="button" href="{% url 'learning_logs:map' %}">Map</a>
			<a class="button" href="{% url 'learning_logs:tavern' %}">Reports</a>
			<a class="button" href="{% url 'learning_logs:citizen-roster' %}">Citizen Roster</a>
		</div>

      <!-- Side Bar -->

      <div style="width: 30%; border-left: 2px solid white; border-right: 2px solid white; padding: 90px 30px; background-color: #ffffff26;">
        <ul style="list-style-type: none; text-align: center;">
          <li>Location ID: </li>
          <li>Number of Citizens in Area: </li>
        </ul>
        <hr>
        <ul style="list-style-type: none; text-align: center;">
          <li>Map Address:</li>
          <li>Area Owner: </li>
          <li>Threat Level: </li>
          <li>Curfew Time: </li>
          <li>Security ID: </li>
        </ul>
      </div>
		</div>
	</div>
	
	<footer id="main-footer" style="background-color: #666;
	border-color: #333;
	border-style: inset;
	border-width: 3px;
	margin: auto;
	margin-top: 10px;
	padding: 5px;">
		<p>Happyville Inc.</p>
	</footer>

</body>
</html>

learning_logs/templates/learning_logs/terminated.html
<!DOCTYPE html>
<html>
<head>
	<title>Terminated</title>
	<link rel="stylesheet" type="text/css" href="/static/learning_logs/style.css">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/pixelated" type="text/css"/> </head>
<body>
	<div class="plain-box">
		<h1>CITIZEN TERMINATED</h1>
		<hr>
		<hr>
		<hr>
	</div>
</body>
</html>